spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: curso-ms-eureka-user
      password: curso-ms-eureka-user

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false